using System;
using System.Collections.Generic;
using System.Linq;
using Code.Gameplay.Objects.ObjectBox;
using Unity.Cinemachine;
using Unity.Netcode;
using UnityEngine;

namespace Code.Gameplay.Character
{
    public class CameraTarget : NetworkBehaviour
    {
        public static CameraTarget Instance;
        
        private CinemachineTargetGroup _cameraTargetGroup;
        [SerializeField] private List<Tracker> _targets = new ();
        private Tracker _mimic;
        
        [Header("Base Tracker")]
        [SerializeField] private Transform _baseTargetTransform;
        [SerializeField] private float _baseTargetRadius;
        [SerializeField] private float _baseTargetWeight;
        private CinemachineTargetGroup.Target _baseTarget;
        private bool _usingBaseTarget;
        
        [Header("Settings")] 
        [SerializeField] private float _radiusBase;
        [SerializeField] private float _radiusGrowth;
        [SerializeField] private float _baseWeight;
        [SerializeField] private float _focusWeight;

        private void Awake()
        {
            if (Instance != null && Instance != this)
            {
                Debug.LogWarning($"There is more than one instance of {GetType().Name}");
                Destroy(gameObject);
                return;
            }
            Instance = this;
            
            _cameraTargetGroup = GetComponent<CinemachineTargetGroup>();
            _baseTarget = new CinemachineTargetGroup.Target
            {
                Object = _baseTargetTransform,
                Radius = _baseTargetRadius,
                Weight = _baseTargetWeight
            };
        }
        
        public void CreateTarget(PlayerController player, bool isPlayer)
        {
            var playerTracker = new GameObject("PlayerTracker-AutoGenerated");
            playerTracker.transform.SetParent(transform);
            CinemachineTargetGroup.Target target = new CinemachineTargetGroup.Target
            {
                Object = playerTracker.transform,
                Radius = _radiusBase,
                Weight = _baseWeight
            };
            
            _targets.Add(new Tracker
            {
                player = player,
                tracker = playerTracker.transform,
                target = target,
                isPlayer = isPlayer,
                mimicPlayer = false,
                internalOutOfBattle = false
            });
            
            _cameraTargetGroup.Targets.Add(target);
        }

        public void RemoveOfViewTarget(Tracker tracker)
        {
            if (_cameraTargetGroup.Targets.Count <= 1 && !_usingBaseTarget)
            {
                _cameraTargetGroup.Targets.Add(_baseTarget);
                _usingBaseTarget = true;
            }
            
            if(_cameraTargetGroup.Targets.Contains(tracker.target)) _cameraTargetGroup.Targets.Remove(tracker.target);
            tracker.outOfView = true;

            if (!tracker.isPlayer) return;
            
            var mimics = _targets.Where(t => !t.isPlayer).ToList();
            if(!mimics.Any()) return;

            _mimic = mimics.Shuffle().FirstOrDefault();
            if (_mimic == null) return;
            
            _mimic.mimicPlayer = true;
            AddToViewTarget(_mimic);
        }

        public void AddToViewTarget(Tracker tracker)
        {
            if (_usingBaseTarget)
            {
                _cameraTargetGroup.Targets.Remove(_baseTarget);
                _usingBaseTarget = false;
            }
            
            _cameraTargetGroup.Targets.Add(tracker.target);
            if(!_cameraTargetGroup.Targets.Contains(tracker.target)) _cameraTargetGroup.Targets.Add(tracker.target);
            tracker.outOfView = false;
            
            if(!tracker.isPlayer || !tracker.mimicPlayer || _mimic == null) return;
            
            _mimic.mimicPlayer = false;
            _mimic = null;
        }

        private void Update()
        {
            UpdateTrackers();
        }

        private void UpdateTrackers()
        {
            foreach (var target in _targets)
            {
                UpdateTracker(target);
            }
            CalculateRadius();
        }

        private void UpdateTracker(Tracker tracker)
        {
            if (!enabled) return;
            
            if(!tracker.player.Invoker.CenterPosition.Request(out var playerPosition).success) return;

            bool inSceneView = CameraBox.Instance.Inside(playerPosition);
            bool inPlayerView = PlayerController.Singleton != null && PlayerController.Singleton.ViewBox.InsideBox(playerPosition);
            bool isPlayer = tracker.isPlayer || tracker.mimicPlayer;
            bool playerInBattle = !tracker.player.outOfBattle.Value && !tracker.player.defeated.Value && !tracker.internalOutOfBattle;

            if(!isPlayer && !tracker.outOfView && (!inSceneView || !inPlayerView || !playerInBattle))
            { 
                RemoveOfViewTarget(tracker);
                return;
            }

            if (!isPlayer && tracker.outOfView && (!inSceneView || !inPlayerView || !playerInBattle))
            {
                return;
            }
            
            if (isPlayer && !inSceneView && playerInBattle)
            {
               tracker.tracker.position = CameraBox.Instance.ConstrainToView(playerPosition);
               tracker.target.Radius = _radiusBase;
               tracker.target.Weight = _baseWeight;
               return;
            }

            if (isPlayer && !playerInBattle && !tracker.outOfView)
            {
                RemoveOfViewTarget(tracker);
                return;
            }

            if (isPlayer && !playerInBattle && tracker.outOfView)
            {
                return;
            }
            
            if(tracker.outOfView) AddToViewTarget(tracker);
            
            float distanceToBox = CameraBox.Instance.Distance(playerPosition);
            
            tracker.tracker.position = playerPosition;
            tracker.target.Radius = Mathf.Clamp(distanceToBox, _radiusBase, _radiusGrowth);
            tracker.target.Weight = tracker.isPlayer ? _focusWeight : _baseWeight;
        }

        private void CalculateRadius()
        {
            float minX = Mathf.Infinity;
            float minY = Mathf.Infinity;
            float maxX = -Mathf.Infinity; 
            float maxY = -Mathf.Infinity;
            
            foreach (var target in _targets)
            {
                if(target.outOfView) continue;
                
                if(minX > target.tracker.position.x) minX = target.tracker.position.x;
                if(minY > target.tracker.position.y) minY = target.tracker.position.y;
                if(maxX < target.tracker.position.x) maxX = target.tracker.position.x;
                if(maxY < target.tracker.position.y) maxY = target.tracker.position.y;
            }
            
            float diffX = maxX - minX;
            float diffY = maxY - minY;

            float currentRadius = _radiusGrowth;
            if (diffX != 0 || diffY != 0)
            {
                float radiusX = (_radiusGrowth - diffX)/2;
                float radiusY = (_radiusGrowth - diffY)/2;
            
                float maxRadius = Mathf.Max(radiusX, radiusY);
                currentRadius = Mathf.Clamp(maxRadius, _radiusBase, _radiusGrowth);
            }
            
            foreach (var target in _targets)
            {
                target.target.Radius = currentRadius;
            }
        }

        public void SetInternalOutOfBattle(PlayerController player, bool internalOutOfBattle)
        {
            Tracker playerTracker = _targets.FirstOrDefault(tracker => tracker.player == player);
            if(playerTracker == null) return;
            playerTracker.internalOutOfBattle = internalOutOfBattle;
        }
    }

    [Serializable]
    public class Tracker
    {
        public PlayerController player;
        public CinemachineTargetGroup.Target target;
        public Transform tracker;
        public bool isPlayer;
        public bool mimicPlayer;
        public bool outOfView;
        public bool internalOutOfBattle;
    }
}